version: '3.8'
services:
  bdbot:
    container_name: bdbot
    build: .
    restart: unless-stopped
    network_mode: host
    env_file:
      - .env
    volumes:
      - ./settings.sqlite3:/app/settings.sqlite3